[package]
name = "automusic"
version = "0.1.0"
edition = "2021"

[dependencies]
directories = "5.0.1"
reqwest = {version = "0.12.7", features = ["blocking", "json"]}
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.128"
sha256 = "1.4.0"
